### ISSUE TITLE
Is anyone else noticing the app lagging?

### ISSUE THREAD

**Issue by theedov** [jordibruin/Swift-Charts-Examples#44]
Is it just Xcode being Xcode, or the sample app is becoming laggy with all those charts? Testing on a simulator since I don't have iOS16 Beta installed.

https://user-images.githubusercontent.com/30866972/173708500-f03c7daa-c64f-4808-8160-f5380cf70053.mov

**Comment by atrinh0** [comment]
Seeing the same.

CPU Spikes to 100% when scrolling.

<img width="353" alt="Screenshot 2022-06-15 at 11 25 18" src="https://user-images.githubusercontent.com/16542463/173805576-76c79488-e866-4619-a51e-0a86ab13c05f.png">

**Comment by jordibruin** [comment]
I wonder if there’s a way we can optimize the charts on the overview page. I have not tested it on device.

Otherwise a toggle to switch between images of the graphs and actual graphs might be a solution?

**Comment by atrinh0** [comment]
Issue appears to be the `List` deallocating cells and redrawing the charts when the user scrolls back into view.

Setting the `List` to a `ScrollView` where every chart is loaded and not released when scrolled out of view gives us a smoother experience.

I am wondering if there is a way to keep the `List` however remove the cell reuse.

https://user-images.githubusercontent.com/16542463/173820017-e0c925f6-f88e-4564-ba2d-43dcbea1732a.mp4

**Comment by jordibruin** [comment]
I looked into rendering an image of the graph with the imageRenderer on first launch and then putting that image instead of the graph. It works okay but I have not found an elegant solution, and it seems the scale is a bit off. Any other suggestions?

We can always just take the screenshots that are in the README and add them to the project instead 🤔

**Comment by atrinh0** [comment]
Potential solution perhaps, https://github.com/jordibruin/Swift-Charts-Examples/pull/52

Thoughts?

**Comment by jordibruin** [comment]
Good one for now! Thanks!
