### ISSUE TITLE
MarkDimension not working as expected. Someone an idea? Is this a bug?

### ISSUE THREAD

**Issue by dasdom** [jordibruin/Swift-Charts-Examples#53]
I tried to add the bottom right chart to the repo but there seems to be bugs in the beta 1.

Reading the documentation of `MarkDimension`, I assume that using `.inset(0)` should fill the step size. If I understand it correctly this should result in rectangles next to each other filling the whole space, as desired. 
<img width="616" alt="Screenshot 2022-06-16 at 22 40 48" src="https://user-images.githubusercontent.com/4385357/174159889-981c9cb9-b48e-4170-a0a1-7e582a677558.png">

But when I create a chart like this:

```
Chart(data) { rectData in
  RectangleMark(x: .value("x", rectData.a),
                y: .value("y", rectData.b),
                width: .inset(0),
                height: .inset(0))
  .foregroundStyle(by: .value("Value", rectData.value))
}
```

the result is an empty chart:

<img width="363" alt="Screenshot 2022-06-16 at 22 46 12" src="https://user-images.githubusercontent.com/4385357/174160677-18888e2d-5cd1-41da-9a76-97719a201fcf.png">

I get it to work with the following code (works but uses hard-coded values for the step size):

```
Chart(data) { rectData in
  RectangleMark(xStart: .value("minA", rectData.a),
                xEnd: .value("maxA", rectData.a + 1),
                yStart: .value("minB", rectData.b),
                yEnd: .value("minB", rectData.b + 1.0))
    .foregroundStyle(by: .value("Value", rectData.value))
}
```

The result:

<img width="363" alt="Screenshot 2022-06-16 at 22 48 29" src="https://user-images.githubusercontent.com/4385357/174161041-c42cf9de-5328-4635-9760-feb9eff30d05.png">

Do I misunderstand `.inset(_:)`?

By the way, `.ratio(1)` doesn't work as well.

**Comment by atrinh0** [comment]
Does `HeatMap` cover this chart type?

**Comment by dasdom** [comment]
I can't find `HeatMap` in the documentation in Xcode. Can you elaborate what you mean?

**Comment by dasdom** [comment]
Oh, haven't seen this. I'll check.

**Comment by atrinh0** [comment]
Keep in mind the `HeatMap` code is one potential way to represent the chart. No idea if that is the way the chart was intended to be used. Happy to see any other solutions anyone can work out and would always welcome the addition for everyone to learn from.
