### ISSUE TITLE
Previews are broken

### ISSUE THREAD

**Issue by jordibruin** [jordibruin/Swift-Charts-Examples#86]
@shiftingsand let me know about:

"FYI, you can’t view previews for *ANY* chart because of this error. "

![IMG_7278](https://user-images.githubusercontent.com/170948/178123963-d083c674-09b4-479a-bcab-c89a60024447.jpeg)
![IMG_3445](https://user-images.githubusercontent.com/170948/178123964-19a01f08-cf23-469a-9adf-cadf452a5e99.jpeg)

**Comment by shiftingsand** [comment]
The 'Text("hello")' is how I got around the problem.

**Comment by atrinh0** [comment]
Fixed in `main` branch.

Issue seems to stem from the chart not handling double values very well.

<img width="567" alt="Screenshot 2022-07-16 at 12 00 21" src="https://user-images.githubusercontent.com/16542463/179352148-9fe32f15-80f0-4e33-a8b3-bad3d06338a2.png">

**Comment by shiftingsand** [comment]
FYI, other charts (such as SoundBars) look like they have the same problem.  Preview won't show.

ambiguous use of operator '-'

----------------------------------------

CompileDylibError: Failed to build SoundBars.swift

Compiling failed: ambiguous use of operator '-'

Swift-Charts-Examples/Swift Charts Examples/Charts/BarCharts/SoundBars.swift:71:30: error: ambiguous use of operator '-'
        .chartYScale(domain: -__designTimeInteger("#8148.[2].[4].property.[0].[0].modifier[2].arg[0].value.[0]", fallback: 1)...__designTimeInteger("#8148.[2].[4].property.[0].[0].modifier[2].arg[0].value.[1]", fallback: 1))
                             ^
Swift.Float16:3:31: note: found this candidate
    prefix public static func - (x: Float16) -> Float16
                              ^
Swift.Float:2:31: note: found this candidate
    prefix public static func - (x: Float) -> Float
                              ^
Swift.Double:2:31: note: found this candidate
    prefix public static func - (x: Double) -> Double
                              ^

**Comment by atrinh0** [comment]
> FYI, other charts (such as SoundBars) look like they have the same problem. Preview won't show.
> 
> ambiguous use of operator '-'
> 
> CompileDylibError: Failed to build SoundBars.swift
> 
> Compiling failed: ambiguous use of operator '-'
> 
> Swift-Charts-Examples/Swift Charts Examples/Charts/BarCharts/SoundBars.swift:71:30: error: ambiguous use of operator '-' .chartYScale(domain: -__designTimeInteger("#8148.[2].[4].property.[0].[0].modifier[2].arg[0].value.[0]", fallback: 1)...__designTimeInteger("#8148.[2].[4].property.[0].[0].modifier[2].arg[0].value.[1]", fallback: 1)) ^ Swift.Float16:3:31: note: found this candidate prefix public static func - (x: Float16) -> Float16 ^ Swift.Float:2:31: note: found this candidate prefix public static func - (x: Float) -> Float ^ Swift.Double:2:31: note: found this candidate prefix public static func - (x: Double) -> Double ^

Soundbars previews fixed via https://github.com/jordibruin/Swift-Charts-Examples/commit/ef801a6958ba6ce413ae7b4a86094676c742a7e4
