### ISSUE TITLE
The project doesn't compile.

### ISSUE THREAD

**Issue by shiftingsand** [jordibruin/Swift-Charts-Examples#90]
Just to be sure I didn't do something incorrectly I cloned the project from scratch into a junk directory.  I got the same compile error.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/31398736/182042080-24ad3fd2-75b4-45df-9258-d7adbaf00ea2.png">

**Comment by atrinh0** [comment]
Still compiles on beta 3

<img width="635" alt="Screenshot 2022-08-02 at 16 21 35" src="https://user-images.githubusercontent.com/16542463/182411379-c49ae53d-72ac-4716-946e-8e2ae9d54c75.png">

However the `EmptyAxisMark` does not appear on the web documentation, https://developer.apple.com/documentation/charts

(Updating to beta 4 now...)

**Comment by atrinh0** [comment]
Confirmed to be related to beta 4.

Fixed on https://github.com/jordibruin/Swift-Charts-Examples/commit/ae4b3b98c57d7cd6f81602a5558f747989d53ad7

**Comment by shiftingsand** [comment]
Thanks looking at it. I should have specified that I was using beta 4.
