### ISSUE TITLE
Couldn't load project. 

### ISSUE THREAD

**Issue by Trupti15** [jordibruin/Swift-Charts-Examples#95]
I downloaded the project and try to open Swift Charts **Examples. xcworkspace**.  
But I can't see anything. Please refer image below.

<img width="1143" alt="Screenshot 2022-11-29 at 10 01 51" src="https://user-images.githubusercontent.com/13196217/204439571-95d5c5d9-95f9-45b1-8055-aba9ca1db814.png">

**Comment by theedov** [comment]
Works for me. Make sure you're running Xcode 14.
<img width="1840" alt="Screenshot 2022-12-01 at 9 45 37 am" src="https://user-images.githubusercontent.com/30866972/204924473-ccaa6fee-62d7-4f5e-8c86-973cae7b946d.png">
